/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: a2b6650e47ecd54155e9077ade43bc69)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	DEPLOY_REVISION: string;
	RESOURCE_ENV: string;
	ACCESS_ISSUER: string;
	ACCESS_AUD: string;
	OWNER_SUB: string;
	APP_ORIGIN: string;
	TEST_ACCESS_JWKS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface LocalEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		DEPLOY_REVISION: string;
		RESOURCE_ENV: string;
		ACCESS_ISSUER: string;
		ACCESS_AUD: string;
		OWNER_SUB: string;
		APP_ORIGIN: string;
		TEST_ACCESS_JWKS: string;
	}
	interface TestEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		DEPLOY_REVISION: string;
		RESOURCE_ENV: string;
		ACCESS_ISSUER: string;
		ACCESS_AUD: string;
		OWNER_SUB: string;
		APP_ORIGIN: string;
		TEST_ACCESS_JWKS: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOY_REVISION" | "RESOURCE_ENV" | "ACCESS_ISSUER" | "ACCESS_AUD" | "OWNER_SUB" | "APP_ORIGIN" | "TEST_ACCESS_JWKS">> {}
}
